server:
  port: 8081
spring:
  application:
    name: xxdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://43.139.189.71:3306/my_dianping?useSSL=false&serverTimezone=UTC
    username: root
    password: 666666
  redis:
    host: 43.139.189.71
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.xxdp.entity # 别名扫描包
logging:
  level:
    com.xxdp: debug
  pattern:
    dateformat: mm:ss.SSS